name: Build binaries

on: [push]

jobs:
  build:
    runs-on: ['self-hosted']

    strategy:
      matrix:
        node-version: ['16']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}        
        
    - name: Install Yarn
      run: npm install -g yarn
        
    - run: yarn install
      name: Install dependencies
    
    - run: yarn build
      name: Build
