name: Linter

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  linter:
    name: Linter (Eslint)

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '15.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: npm run lint
