# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build binaries for Linux/Windows/MacOS and create Github release

on:
  push:
    branches: [ master ]

jobs:
  build_binaries_and_create_release:
    name: Build binaries for ${{ matrix.os }} and push them to Github release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 15.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build binaries (auto Github release creation)
        run: yarn build --publish always
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
