# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build binaries for Linux/Windows/MacOS and create release

on:
  push:
    branches: [ master ]

jobs:
  build_binaries_and_create_release:
    name: Build release for ${{ matrix.os }} and create release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set git to use LF
        run: |
            git config --global core.autocrlf false
            git config --global core.eol lf

      - uses: actions/checkout@v2
        name: Clone repo

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build binaries (auto create release)
        run: yarn build --publish always
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
